apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: telegram-to-managed-kafka
  namespace: demo
  labels:
    app: telegram-to-managed-kafka
    app.kubernetes.io/instance: telegram-to-managed-kafka
    app.kubernetes.io/component: telegram-to-managed-kafka
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  integration:
    traits:
      service-binding:
        configuration:
          serviceBindings:
          - rhoas.redhat.com/v1alpha1:KafkaConnection:kafka-summit-apac
  source:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: telegram-source
    properties:
      authorizationToken: 'YOUR_TOKEN'
      chatId: 'YOUR_ID'
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: managed-kafka-sink
    properties:
      topic: telegram-in
    
